// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmskpmzsgiskztveylgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtc2twbXpzZ2lza3p0dmV5bGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzA1NTAsImV4cCI6MjA1NjQwNjU1MH0.c56Moi6vmqhyrMLsacUjyEtPxIiMLYvmeB6oiSW3JYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);